import mongoose from 'mongoose'
import 'dotenv/config'
import Accommodation from '../models/Accommodation.js'

const img = (seed) => `https://picsum.photos/seed/${seed}/800/600`

const ACCOMMODATIONS = [
  // ── 부산 (광안리해수욕장 포함) ───────────────────────────────────────────
  {
    title: '해운대 바다뷰 펜션',
    location: '부산광역시 해운대구 광안리해수욕장',
    type: 'entire_home',
    bedrooms: 2,
    beds: 4,
    pricePerNight: 350000,
    rating: 4.92,
    reviewCount: 87,
    maxGuests: 6,
    tag: '게스트 선호',
    description: '해운대 해변에서 도보 5분, 탁 트인 바다 전망의 독채 펜션',
    images: [img('busan1'), img('busan1b'), img('busan1c')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '광안리 해변 독채',
    location: '부산광역시 수영구 광안리해수욕장',
    type: 'entire_home',
    bedrooms: 1,
    beds: 2,
    pricePerNight: 185000,
    rating: 4.85,
    reviewCount: 43,
    maxGuests: 4,
    tag: '게스트 선호',
    description: '광안리 해수욕장 바로 앞 해변가 독채, 오션뷰 발코니 포함',
    images: [img('busan2'), img('busan2b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '부산 남포동 모던 아파트',
    location: '부산광역시 중구 남포동',
    type: 'room',
    bedrooms: 1,
    beds: 1,
    pricePerNight: 95000,
    rating: 4.7,
    reviewCount: 28,
    maxGuests: 2,
    tag: null,
    description: '남포동 시내 중심가 접근성 좋은 모던 원룸, 지하철 도보 2분',
    images: [img('busan3')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '센텀시티 프리미엄 스위트',
    location: '부산광역시 해운대구 센텀시티',
    type: 'entire_home',
    bedrooms: 3,
    beds: 4,
    pricePerNight: 680000,
    rating: 4.95,
    reviewCount: 112,
    maxGuests: 8,
    tag: '슈퍼호스트',
    description: '센텀시티 고층 스위트, BEXCO 도보 5분, 영화의 전당 조망',
    images: [img('busan4'), img('busan4b'), img('busan4c')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '광안대교 야경 오션뷰 아파트',
    location: '부산광역시 수영구 광안리해수욕장',
    type: 'entire_home',
    bedrooms: 2,
    beds: 2,
    pricePerNight: 310000,
    rating: 4.82,
    reviewCount: 56,
    maxGuests: 4,
    tag: null,
    description: '광안대교 야경이 한눈에 보이는 오션뷰 아파트, 커플·가족 추천',
    images: [img('busan5'), img('busan5b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '해운대 럭셔리 풀빌라',
    location: '부산광역시 해운대구',
    type: 'entire_home',
    bedrooms: 3,
    beds: 5,
    pricePerNight: 1200000,
    rating: 5.0,
    reviewCount: 34,
    maxGuests: 8,
    tag: '슈퍼호스트',
    description: '프라이빗 풀 딸린 해운대 럭셔리 빌라, 가족·단체 모임 최적',
    images: [img('busan6'), img('busan6b'), img('busan6c')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '기장 바다 별장',
    location: '부산광역시 기장군',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 450000,
    rating: 4.91,
    reviewCount: 71,
    maxGuests: 5,
    tag: '게스트 선호',
    description: '기장 앞바다 전망의 조용한 별장, 신선한 회 주문 가능한 어촌 마을',
    images: [img('busan7'), img('busan7b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '부산 시내 코지 게스트룸',
    location: '부산광역시 부산진구',
    type: 'room',
    bedrooms: 1,
    beds: 1,
    pricePerNight: 78000,
    rating: 4.65,
    reviewCount: 19,
    maxGuests: 2,
    tag: null,
    description: '부산 시내 코지한 게스트룸, 서면 맛집 거리 도보권',
    images: [img('busan8')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },

  // ── 제주 ────────────────────────────────────────────────────────────────
  {
    title: '서귀포 오션뷰 펜션',
    location: '제주특별자치도 서귀포시',
    type: 'entire_home',
    bedrooms: 2,
    beds: 4,
    pricePerNight: 550000,
    rating: 4.94,
    reviewCount: 203,
    maxGuests: 6,
    tag: '게스트 선호',
    description: '제주 산방산뷰·서툰가족_3(실내온수풀, 바베큐, 넷플릭스)',
    images: [img('jeju1'), img('jeju1b'), img('jeju1c')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '제주 자연 속 힐링 독채',
    location: '제주특별자치도 제주시',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 380000,
    rating: 4.88,
    reviewCount: 89,
    maxGuests: 5,
    tag: '게스트 선호',
    description: '아이 안심! 숲뷰 독채 | 사계절 무료 온수 키즈풀, 바베큐',
    images: [img('jeju2'), img('jeju2b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '제주 타운하우스',
    location: '제주특별자치도 서귀포시',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 148000,
    rating: 5.0,
    reviewCount: 92,
    maxGuests: 4,
    tag: '게스트 선호',
    description: '스테이베다니/확~트인 바다뷰/일출일몰/스파/BBQ/무료주차',
    images: [img('jeju3'), img('jeju3b'), img('jeju3c')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '서귀포시의 집',
    location: '제주특별자치도 서귀포시',
    type: 'entire_home',
    bedrooms: 2,
    beds: 2,
    pricePerNight: 440000,
    rating: 4.96,
    reviewCount: 46,
    maxGuests: 4,
    tag: '게스트 선호',
    description: '제주_산방산뷰_가족시간(실내온수풀, 바베큐, 넷플릭스)',
    images: [img('jeju4'), img('jeju4b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '함덕 해변 가까운 독채',
    location: '제주특별자치도 제주시 조천읍 함덕',
    type: 'entire_home',
    bedrooms: 1,
    beds: 2,
    pricePerNight: 255000,
    rating: 4.83,
    reviewCount: 61,
    maxGuests: 4,
    tag: null,
    description: '함덕 해수욕장 도보 3분, 에메랄드 바다가 보이는 독채',
    images: [img('jeju5'), img('jeju5b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '제주 감귤농장 하우스',
    location: '제주특별자치도 서귀포시 남원읍',
    type: 'entire_home',
    bedrooms: 2,
    beds: 4,
    pricePerNight: 420000,
    rating: 4.91,
    reviewCount: 135,
    maxGuests: 6,
    tag: '게스트 선호',
    description: '감귤 직접 따기 체험 가능한 제주 농장 독채, 바비큐 시설 포함',
    images: [img('jeju6'), img('jeju6b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '제주 협재 해변 풀빌라',
    location: '제주특별자치도 제주시 한림읍 협재',
    type: 'entire_home',
    bedrooms: 3,
    beds: 6,
    pricePerNight: 1500000,
    rating: 5.0,
    reviewCount: 48,
    maxGuests: 10,
    tag: '슈퍼호스트',
    description: '협재 에메랄드 바다 전망 프라이빗 풀빌라, 단체·가족 최적',
    images: [img('jeju7'), img('jeju7b'), img('jeju7c')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '성산일출봉 뷰 펜션',
    location: '제주특별자치도 서귀포시 성산읍',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 480000,
    rating: 4.86,
    reviewCount: 77,
    maxGuests: 5,
    tag: null,
    description: '성산일출봉 조망 가능한 펜션, 일출 명소 도보 10분',
    images: [img('jeju8'), img('jeju8b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '제주 게스트용 별채',
    location: '제주특별자치도 서귀포시',
    type: 'room',
    bedrooms: 1,
    beds: 1,
    pricePerNight: 238000,
    rating: 4.99,
    reviewCount: 275,
    maxGuests: 2,
    tag: '게스트 선호',
    description: '하얀집(별채), 협재바다 1초컷, 협재 해수욕장 도보 1분',
    images: [img('jeju9'), img('jeju9b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },

  // ── 속초시 ──────────────────────────────────────────────────────────────
  {
    title: '속초 청초호 뷰 독채',
    location: '강원도 속초시 청초호',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 290000,
    rating: 4.89,
    reviewCount: 54,
    maxGuests: 5,
    tag: '게스트 선호',
    description: '청초호 수변 전망의 아늑한 독채, 속초 아이파크 도보 10분',
    images: [img('sokcho1'), img('sokcho1b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '설악산 자연 속 힐링 하우스',
    location: '강원도 속초시 설악동',
    type: 'entire_home',
    bedrooms: 2,
    beds: 4,
    pricePerNight: 375000,
    rating: 4.92,
    reviewCount: 98,
    maxGuests: 6,
    tag: '게스트 선호',
    description: '설악산 케이블카 도보 5분, 사계절 자연을 만끽하는 힐링 독채',
    images: [img('sokcho2'), img('sokcho2b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '속초 해변 코지 룸',
    location: '강원도 속초시 속초해수욕장',
    type: 'room',
    bedrooms: 1,
    beds: 1,
    pricePerNight: 115000,
    rating: 4.73,
    reviewCount: 22,
    maxGuests: 2,
    tag: null,
    description: '속초해수욕장 도보 3분 코지 룸, 저렴하고 깔끔한 숙소',
    images: [img('sokcho3')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '속초 럭셔리 펜션',
    location: '강원도 속초시',
    type: 'entire_home',
    bedrooms: 3,
    beds: 5,
    pricePerNight: 750000,
    rating: 4.95,
    reviewCount: 83,
    maxGuests: 8,
    tag: '슈퍼호스트',
    description: '가족·단체 여행 최적의 넓은 독채 펜션, 바베큐·노래방 구비',
    images: [img('sokcho4'), img('sokcho4b'), img('sokcho4c')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '설악 뷰 글램핑 독채',
    location: '강원도 속초시 설악동',
    type: 'entire_home',
    bedrooms: 1,
    beds: 2,
    pricePerNight: 340000,
    rating: 4.87,
    reviewCount: 41,
    maxGuests: 4,
    tag: null,
    description: '설악산 뷰 프리미엄 글램핑 독채, 성수기 한정 특별 숙소',
    images: [img('sokcho5'), img('sokcho5b')],
    availableFrom: new Date('2026-04-01'),
    availableTo: new Date('2026-11-30'),
  },
  {
    title: '구조암의 게스트용 별채',
    location: '강원도 속초시',
    type: 'entire_home',
    bedrooms: 1,
    beds: 2,
    pricePerNight: 125000,
    rating: 4.81,
    reviewCount: 121,
    maxGuests: 2,
    tag: '게스트 선호',
    description: '월정바다 바로앞, 아늑한 제주옛집 ( 바다앞 / 마당 / 테라스 / BBQ)',
    images: [img('sokcho6'), img('sokcho6b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },

  // ── 강릉시 ──────────────────────────────────────────────────────────────
  {
    title: '강릉 경포대 뷰 독채',
    location: '강원도 강릉시 경포대',
    type: 'entire_home',
    bedrooms: 2,
    beds: 4,
    pricePerNight: 320000,
    rating: 4.9,
    reviewCount: 67,
    maxGuests: 6,
    tag: '게스트 선호',
    description: '경포대 호수 전망의 넓은 독채, 강릉 커피 거리 도보 15분',
    images: [img('gangneung1'), img('gangneung1b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '주문진 해변 펜션',
    location: '강원도 강릉시 주문진읍',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 270000,
    rating: 4.85,
    reviewCount: 49,
    maxGuests: 5,
    tag: null,
    description: '주문진 해수욕장 도보 2분, 펜션 내 바베큐 가능',
    images: [img('gangneung2'), img('gangneung2b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '오죽헌 근처 한옥',
    location: '강원도 강릉시 죽헌동',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 580000,
    rating: 4.93,
    reviewCount: 38,
    maxGuests: 5,
    tag: '게스트 선호',
    description: '오죽헌 도보 5분 전통 한옥 독채, 바닥 온돌 난방·마당 제공',
    images: [img('gangneung3'), img('gangneung3b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '강릉 경포 럭셔리 빌라',
    location: '강원도 강릉시 경포동',
    type: 'entire_home',
    bedrooms: 3,
    beds: 5,
    pricePerNight: 870000,
    rating: 4.96,
    reviewCount: 92,
    maxGuests: 8,
    tag: '슈퍼호스트',
    description: '경포해변 오션뷰 럭셔리 빌라, 단체 여행·기념일 특별 숙소',
    images: [img('gangneung4'), img('gangneung4b'), img('gangneung4c')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '안목해변 독채',
    location: '강원도 강릉시 견소동 안목해변',
    type: 'entire_home',
    bedrooms: 1,
    beds: 2,
    pricePerNight: 245000,
    rating: 4.83,
    reviewCount: 33,
    maxGuests: 4,
    tag: null,
    description: '안목 커피거리 바로 옆, 바다 전망 아늑한 독채',
    images: [img('gangneung5'), img('gangneung5b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '강릉 모던 스튜디오',
    location: '강원도 강릉시 교동',
    type: 'room',
    bedrooms: 1,
    beds: 1,
    pricePerNight: 105000,
    rating: 4.71,
    reviewCount: 15,
    maxGuests: 2,
    tag: null,
    description: '강릉 시내 접근성 좋은 모던 스튜디오, 혼자 또는 커플 여행 추천',
    images: [img('gangneung6')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },

  // ── 여수시 ──────────────────────────────────────────────────────────────
  {
    title: '여수 엑스포 뷰 독채',
    location: '전라남도 여수시 수정동',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 300000,
    rating: 4.88,
    reviewCount: 74,
    maxGuests: 5,
    tag: '게스트 선호',
    description: '여수세계박람회장 조망, 밤바다 야경 최고의 독채',
    images: [img('yeosu1'), img('yeosu1b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '돌산도 바다 펜션',
    location: '전라남도 여수시 돌산읍',
    type: 'entire_home',
    bedrooms: 2,
    beds: 4,
    pricePerNight: 420000,
    rating: 4.91,
    reviewCount: 58,
    maxGuests: 6,
    tag: null,
    description: '돌산도 해안 도로 바로 옆 펜션, 바다 낚시 체험 가능',
    images: [img('yeosu2'), img('yeosu2b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '여수 밤바다 뷰 아파트',
    location: '전라남도 여수시 중앙동',
    type: 'entire_home',
    bedrooms: 1,
    beds: 2,
    pricePerNight: 235000,
    rating: 4.82,
    reviewCount: 31,
    maxGuests: 3,
    tag: null,
    description: '여수 밤바다 노래의 그 바다를 방에서 직접! 오션뷰 아파트',
    images: [img('yeosu3'), img('yeosu3b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '여수 고급 풀빌라',
    location: '전라남도 여수시 웅천동',
    type: 'entire_home',
    bedrooms: 3,
    beds: 5,
    pricePerNight: 1100000,
    rating: 4.98,
    reviewCount: 62,
    maxGuests: 8,
    tag: '슈퍼호스트',
    description: '오션뷰 프라이빗 풀 딸린 고급 빌라, 특별한 날을 위한 숙소',
    images: [img('yeosu4'), img('yeosu4b'), img('yeosu4c')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '향일암 근처 독채',
    location: '전라남도 여수시 돌산읍 향일암',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 360000,
    rating: 4.86,
    reviewCount: 45,
    maxGuests: 5,
    tag: null,
    description: '일출 명소 향일암 도보 10분, 조용한 바다 마을의 독채',
    images: [img('yeosu5'), img('yeosu5b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '여수 시내 모던 룸',
    location: '전라남도 여수시 학동',
    type: 'room',
    bedrooms: 1,
    beds: 1,
    pricePerNight: 108000,
    rating: 4.69,
    reviewCount: 17,
    maxGuests: 2,
    tag: null,
    description: '여수 시내 중심 교통 편리한 모던 룸, 여수 해산물 거리 도보권',
    images: [img('yeosu6')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },

  // ── 오사카시 ────────────────────────────────────────────────────────────
  {
    title: '오사카 도톤보리 아파트',
    location: '일본 오사카부 오사카시 도톤보리',
    type: 'room',
    bedrooms: 1,
    beds: 1,
    pricePerNight: 152000,
    rating: 4.83,
    reviewCount: 88,
    maxGuests: 2,
    tag: null,
    description: '도톤보리 도보 2분, 번화가 중심의 모던 아파트',
    images: [img('osaka1'), img('osaka1b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '오사카성 근처 아파트',
    location: '일본 오사카부 오사카시 오사카성',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 385000,
    rating: 4.89,
    reviewCount: 103,
    maxGuests: 4,
    tag: '게스트 선호',
    description: '오사카성 도보 7분, 넓고 깔끔한 일본식 아파트',
    images: [img('osaka2'), img('osaka2b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '난바 역 근처 스튜디오',
    location: '일본 오사카부 오사카시 난바',
    type: 'room',
    bedrooms: 1,
    beds: 1,
    pricePerNight: 132000,
    rating: 4.74,
    reviewCount: 55,
    maxGuests: 2,
    tag: null,
    description: '난바 역 도보 3분, 쇼핑·먹거리 중심의 알짜배기 스튜디오',
    images: [img('osaka3')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '오사카 프리미엄 타워뷰',
    location: '일본 오사카부 오사카시 우메다',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 560000,
    rating: 4.92,
    reviewCount: 77,
    maxGuests: 4,
    tag: '슈퍼호스트',
    description: '오사카 스카이빌딩 조망, 고층 타워뷰 프리미엄 아파트',
    images: [img('osaka4'), img('osaka4b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '우메다 모던 아파트',
    location: '일본 오사카부 오사카시 우메다',
    type: 'room',
    bedrooms: 1,
    beds: 2,
    pricePerNight: 198000,
    rating: 4.8,
    reviewCount: 44,
    maxGuests: 3,
    tag: null,
    description: '우메다 쇼핑몰 도보 5분, 깔끔하고 넓은 모던 아파트',
    images: [img('osaka5'), img('osaka5b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '오사카 고급 펜트하우스',
    location: '일본 오사카부 오사카시 신사이바시',
    type: 'entire_home',
    bedrooms: 3,
    beds: 4,
    pricePerNight: 950000,
    rating: 4.96,
    reviewCount: 29,
    maxGuests: 6,
    tag: '슈퍼호스트',
    description: '오사카 최고층 펜트하우스, 360도 파노라마 야경 럭셔리 숙소',
    images: [img('osaka6'), img('osaka6b'), img('osaka6c')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
  {
    title: '신사이바시 복층 독채',
    location: '일본 오사카부 오사카시 신사이바시',
    type: 'entire_home',
    bedrooms: 2,
    beds: 3,
    pricePerNight: 475000,
    rating: 4.87,
    reviewCount: 61,
    maxGuests: 5,
    tag: '게스트 선호',
    description: '신사이바시 쇼핑 거리 도보 1분, 복층 구조 감성 독채',
    images: [img('osaka7'), img('osaka7b')],
    availableFrom: new Date('2026-01-01'),
    availableTo: new Date('2027-12-31'),
  },
]

async function seed() {
  const uri = process.env.MONGODB_URI
  if (!uri) throw new Error('MONGODB_URI is not defined in environment variables')
  try {
    await mongoose.connect(uri)
    console.log('MongoDB connected')

    await Accommodation.deleteMany({})
    console.log('Cleared existing accommodations')

    await Accommodation.insertMany(ACCOMMODATIONS)
    console.log(`Inserted ${ACCOMMODATIONS.length} accommodations`)

    await mongoose.disconnect()
    console.log('Done')
  } catch (err) {
    console.error(err)
    process.exit(1)
  }
}

seed()
